language: java
jdk:
 - openjdk13
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "softwaretalks-1" 
    token:
      secure: "ByOiDslVR8Jx1comsqUFFEp/RvOV85LKfuGOhcxba6hH4l+7nJ1bYUcGjichHC5IhagW6GCigQ/kooZm6PNRkJoPMvs/TM1thL6ewBHQfqQY+Pg/vin9TV2M0fMybVUoVIh9dbZ5F5ooYcFVqivxLw9gLa/ZbwRgEcdcCEPVGctkijoghLgUVQesHpd0tHnqqzsqlOU/das2RMhEyijDdXYjEYk22zNl02xX5Rn2lxqh3B9COQrFIG3TFhVkkffmjOIlptuaXWFGLxm1Ibyh/DBc7KJvbo1+00VHhJlrl5W4jvkN2J2BrLKERF3+HEOgKqnqxYIZC+9pKM7jAPPfgfnhtvWNczxgszEGpnnuASubxNIDCmmSVq0Yd2YTkSma95WJUDKKBM57TkG0Ih0PdT2NakfW9tgkufJP49yx//mIUMqVCrrCQR4Zc+y7LMAgSNlolqYEep6+mzh8ir5gEKPck37KwWobnZoBDh+Zxkvh0y5nTWTfJpq3foF0bJ2iDUBVzRrDGgmGU5ztPxkuNO13vH1NjzNtKjPXNeZMkVk+DrzyY+JGVhXWYyGTxh0INDXwqphFU0rLMQen1WOhQQ+W4acfmd/nzhqOC6NcGriHokLZlBD9uBAMmkq0N+jOZoXayKmfLWsVNM1lwDRamk7q6Jjz5pqvRY3/C4ZyqnA="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Dsonar.projectKey=softwaretalks_jangul
